compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@nx/jest@*":
    peerDependenciesMeta:
      nx:
        optional: true
  jest-config@*:
    dependencies:
      ts-node: "*"
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
