yarnPath: .yarn/releases/yarn-3.6.0.cjs
packageExtensions:
  "@nx/jest@*":
    peerDependenciesMeta:
      nx:
        optional: true
  jest-config@*:
    dependencies:
      ts-node: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
